### ISSUE TITLE
Components are not being detected

### ISSUE THREAD

**Issue by Joe23232** [sdfgeoff/blender_bevy_toolkit#11]
@sdfgeoff Hey man.

So I uninstalled the all addon and I installed the new addon.

> What you put inside the JSON files depends on what components you have in your game.
Eg from the example above:

So I added this exact same script:

```json
{
    "name": "Engine",
    "description": "Used to apply thrust to an object",
    "id": "space_ship_engine",
    "struct": "game::ship_parts::engine::Engine",
    "fields": [
        {
            "field": "max_thrust_newtons", 
            "type": "f64", 
            "default": 10.0,
            "description": "The max amount of force the engine can apply, measured in Newtons"
        }
    ]
}
```

into a file called `windmill.json` inside the folder `component_definitions`. In the outside directory of `component_definitions` I have a file called `Demo.blend`. And I still can't see any components to add.

![image](https://user-images.githubusercontent.com/34926497/132936242-47b276ed-babf-4d1b-a87d-4beb1922e791.png)

not too sure why this is happening?

**Comment by sdfgeoff** [comment]
Can you look at the output from the console?
In windows use view->toggle system console

**Comment by sdfgeoff** [comment]
I'm glad its working! (Or at least working more)

I define some default components. Many of them you can't see (eg mesh, heirarchy, object name), and a few you can (the physics ones).

Do I understand your previous post right that you have two 'component definitions' folders? That may be confusing it.

You should have (for example)
```
MyGame
 - component_definitions
     - windmill.json
 - mymodel1.blend
 - mymodel2.blend
 ```

**Comment by Joe23232** [comment]
@sdfgeoff Hey mate.

> I define some default components. Many of them you can't see (eg mesh, heirarchy, object name), and a few you can (the physics ones).

Ah right makes sense.


> You should have (for example)

Its structured like this (similar to what you have said)

```
MyGame
 - component_definitions
     - windmill.json
 - Demo.blend
```
So yeah not too sure why this is happening?

**Comment by sdfgeoff** [comment]
I just noticed that ... it is working. Look on line 2 of the windmill.json file:
```
"name": "Engine"
```
Try changing that to 'Windmill' and re-opening blender

:wink:

**Comment by Joe23232** [comment]
@sdfgeoff Didn't realise that mate :)

Thanks for that mate =D


looking forward to using your tool now, honestly I think your tool should be the main Bevy GUI tool to be honest :)
