### ISSUE TITLE
Adding enum component types

### ISSUE THREAD

**Issue by piedoom** [sdfgeoff/blender_bevy_toolkit#14]
Hey there - as my game is using v0.11 of rapier, I'm trying to create my own `component_definitions`. As of 0.11, many of the larger structures have been broken down for easier usage within bevy's ECS. That includes components such as [`RigidBodyType`](https://rapier.rs/docs/user_guides/bevy_plugin/rigid_bodies#rigid-body-type) that are a numbered enum. 

In the custom components file, I see a struct must be provided with fields. Is there any way currently to define enum components? Perhaps through a py file? (I'm thinking that it might be best to add *all* components needed for a rigidbody/collider at once, so maybe a py file can define that)

**Comment by sdfgeoff** [comment]
Currently all components must be structs - which I think is generically true in bevy.

While the interface can display an enum, the backing storage is still an integer. For example for bevy-rapier (whatever old version is in this repo), I had the struct: 

The struct that the blender plugin creates
```rust
pub struct RigidBodyDescription {
    /// Because we can't export enums yet, this is encoded as a u8
    ///  0 => dynamic
    ///  1 => static
    ///  2 => kinematic
    pub body_status: u8,

<< snip >>
```
With definition:
```json
{
    "name": "RigidBody",
    "description": "Makes this object obey physics",
    "id": "rapier_rigid_body",
    "struct": "blender_bevy_toolkit::rapier_physics::RigidBodyDescription",
    "fields": [
        {
            "field": "body_status", 
            "type": "u8enum", 
            "default": ["dynamic", "static", "kinematic"],
            "description": "Dynamic bodies respond to forces. Static bodies do not move. Kinematic bodies must be moved manually but internally track velocity so they push other dynamic bodies properly"
        },
<< snip >>
```

And then at runtime:
```rust
/// Converts a RigidBodyDescription into a rapier::dynamics::RigidBodyBuilder. This allows
/// RigidBodyBuilders to be created from a file using bevies Reflection system and scene format
pub fn body_description_to_builder(
    mut commands: Commands,
    body_desc_query: Query<(&RigidBodyDescription, Entity, &Transform)>,
) {
    for (body_desc, entity, transform) in body_desc_query.iter() {
        commands.entity(entity).remove::<RigidBodyDescription>();
        
        << snip >>
        let body_status = match body_desc.body_status {
            0 => BodyStatus::Dynamic,
            1 => BodyStatus::Static,
            2 => BodyStatus::Kinematic,
            _ => panic!("Unknown body status"),
        };

        << snip >>

        let rigid_body_builder = RigidBodyBuilder::new(body_status)
            .position(position)
            .linear_damping(body_desc.damping_linear)
            .angular_damping(body_desc.damping_angular)
            .ccd_enabled(body_desc.ccd_enable)
            .can_sleep(body_desc.sleep_allow)
            .additional_mass(body_desc.mass_extra)
            .additional_principal_angular_inertia(inertia_vec);

        commands.entity(entity).insert(rigid_body_builder);
```


It was done this way because at the time, Bevy didn't support `Reflect` on enums. That's probably changed now.


When you do an integration with the new bevy-rapier, I'm super interested in including it into this repo, so please ping back when you've got something working.

**Comment by piedoom** [comment]
thank you for the detailed response, it's much appreciated! Closing as the original issue is solved but if I happen to run into any more info about `Reflect` on enums I'll ping back - and likewise if I have any success with new rapier.

**Comment by piedoom** [comment]
I juuuuuust got success with some in game collisions finally - haven't tested everything and unsure if this code is of any use but I posed the work [here](https://github.com/piedoom/blender_bevy_toolkit/commit/a8cc1066d868bac33ee3acfd0bd8e4d48400506f)

**Comment by piedoom** [comment]
Got some progress done which I published to my fork, unsure if it is of any use. I think the components work but I got the positions wrong as it glitches for non-zero transforms. Looking into that tomorrow but in the meantime it appears to properly add colliders at least
