### ISSUE TITLE
Is this similar to the Armory 3D game engine?

### ISSUE THREAD

**Issue by Joe23232** [sdfgeoff/blender_bevy_toolkit#8]
Hey mate, this project seems pretty interesting, but I am curious to know is your project similar to the [Armory3D game engine](https://armory3d.org/)?

**Comment by sdfgeoff** [comment]
I haven't worked with Armoury much, but my guess is No. Armoury aims to do everything inside of the blender UI. This toolkit simply allows exporting of geometry and components. The game development itself is done in rust/bevy. 

If you're looking to build a game, probably use armoury.

Also, this is now out of date with the rapier physics engine, so I need to update it at some point....

**Comment by Joe23232** [comment]
> I haven't worked with Armoury much, but my guess is No. Armoury aims to do everything inside of the blender UI. This toolkit simply allows exporting of geometry and components. The game development itself is done in rust/bevy.

Am I able to attatch Rust code on a particular object and code it to maybe move or something, like what Unity does?

**Comment by sdfgeoff** [comment]
Not directly. You can't "select a rust file" to run on an object. What you can do is link a component and it's configuration (aka a rust struct) to a blender entity. Then a system can use that component as described here: https://bevyengine.org/learn/book/getting-started/ecs/

So for example you may write a system that accesses both a tag exported blender component and bevy's internal `Transform` component. Using a true ECS  like bevy's (as opposed to Unities more OO-stle ECS) is a bit of a mind-shift.

**Comment by Joe23232** [comment]
> Not directly. You can't "select a rust file" to run on an object. What you can do is link a component and it's configuration (aka a rust struct) to a blender entity. Then a system can use that component as described here: https://bevyengine.org/learn/book/getting-started/ecs/

I hope this doesn't lead to too much boilerplate code?

**Comment by sdfgeoff** [comment]
Unfortunately I haven't found a way to "export" rusts structs to blender, and even if you could, blender needs some additional code to figure out what UI to display to the user. As a result all the components are "replicated" in a JSON format that tells blender how to export them.

Perhaps this video would clear up what this plugin can do:
https://www.youtube.com/watch?v=oTx4hJF-ees

**Comment by Joe23232** [comment]
Interesting mate.

So then in this case lets just say I have a cube and a plane. If I export it to Bevy, then is it possible to control the cube separately?

**Comment by sdfgeoff** [comment]
Yup. If you assign them different components then you can have a system operate selectively on those components. 
Eg if one object has the component "Player" then you can write a system in bevy that only runs on objects with the Player component.

**Comment by Joe23232** [comment]
@sdfgeoff Thanks mate =D
